from __future__ import annotations

import json
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


@dataclass
class StageWriter:
    stage: str
    dataset_key: str
    output_path: Path
    _fp: Any = field(default=None, repr=False)

    def open(self) -> None:
        self.output_path.parent.mkdir(parents=True, exist_ok=True)
        self._fp = self.output_path.open("w", encoding="utf-8")

    def write(self, record: dict[str, Any]) -> None:
        assert self._fp is not None
        self._fp.write(json.dumps(record, ensure_ascii=False) + "\n")

    def close(self) -> None:
        if self._fp is not None:
            self._fp.close()
            self._fp = None


@dataclass
class ConvertReport:
    dataset: str
    role: str
    stages: dict[str, int] = field(default_factory=dict)
    skipped: dict[str, int] = field(default_factory=lambda: defaultdict(int))
    output_files: dict[str, Path] = field(default_factory=dict)
    dry_run: bool = False

    @property
    def total_written(self) -> int:
        return max(self.stages.values()) if self.stages else 0


def persist_manifest(
    manifest: dict[str, Any],
    manifest_path: Path,
    registry_path: Path,
    project_root: Path,
) -> None:
    registry_lines = [
        "# Auto-generated by tower convert. Copy into NEO neo/data/__init__.py data_dict.",
        "",
        "data_dict = {",
    ]
    for dataset_key in sorted(manifest):
        entry = manifest[dataset_key]
        for stage, rel in sorted(entry.get("stages", {}).items()):
            reg_key = f"{dataset_key}_{stage}"
            abs_path = (project_root / rel).resolve()
            registry_lines.append(f'    "{reg_key}": {{')
            registry_lines.append(f'        "annotation_path": "{abs_path}",')
            registry_lines.append('        "data_path": "",')
            registry_lines.append("    },")
    registry_lines.append("}")

    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    registry_path.write_text("\n".join(registry_lines) + "\n", encoding="utf-8")


def _count_jsonl_lines(path: Path) -> int:
    with path.open(encoding="utf-8") as fp:
        return sum(1 for _ in fp)


def refresh_manifest_from_disk(project_root: Path) -> dict[str, Any]:
    """Rebuild manifest from existing data/processed/{pt,mt,sft}/*.jsonl files."""
    from tower.config import PROCESSED_DIR, load_dataset_specs

    specs = load_dataset_specs()
    manifest: dict[str, Any] = {}
    for stage in ("pt", "mt", "sft"):
        stage_dir = PROCESSED_DIR / stage
        if not stage_dir.is_dir():
            continue
        for jsonl_path in sorted(stage_dir.glob("*.jsonl")):
            dataset_key = jsonl_path.stem
            rel_path = str(jsonl_path.relative_to(project_root))
            sample_count = _count_jsonl_lines(jsonl_path)
            spec = specs.get(dataset_key)
            entry = manifest.setdefault(
                dataset_key,
                {
                    "stages": {},
                    "samples": 0,
                    "role": spec.role if spec else "",
                    "skipped": {},
                },
            )
            entry["stages"][stage] = rel_path
            entry["samples"] = max(entry["samples"], sample_count)
            if spec and not entry["role"]:
                entry["role"] = spec.role
    return manifest


def write_manifest(
    reports: list[ConvertReport],
    manifest_path: Path,
    registry_path: Path,
    project_root: Path,
) -> None:
    manifest: dict[str, Any] = {}
    if manifest_path.is_file():
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))

    for report in reports:
        if report.dry_run or not report.output_files:
            continue
        rel_stages = {
            stage: str(path.relative_to(project_root))
            for stage, path in report.output_files.items()
        }
        manifest[report.dataset] = {
            "stages": rel_stages,
            "samples": report.total_written,
            "role": report.role,
            "skipped": dict(report.skipped),
        }

    persist_manifest(manifest, manifest_path, registry_path, project_root)
