from __future__ import annotations

import json
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


@dataclass
class StageWriter:
    stage: str
    dataset_key: str
    output_path: Path
    _fp: Any = field(default=None, repr=False)

    def open(self) -> None:
        self.output_path.parent.mkdir(parents=True, exist_ok=True)
        self._fp = self.output_path.open("w", encoding="utf-8")

    def write(self, record: dict[str, Any]) -> None:
        assert self._fp is not None
        self._fp.write(json.dumps(record, ensure_ascii=False) + "\n")

    def close(self) -> None:
        if self._fp is not None:
            self._fp.close()
            self._fp = None


@dataclass
class ConvertReport:
    dataset: str
    role: str
    stages: dict[str, int] = field(default_factory=dict)
    skipped: dict[str, int] = field(default_factory=lambda: defaultdict(int))
    output_files: dict[str, Path] = field(default_factory=dict)
    dry_run: bool = False

    @property
    def total_written(self) -> int:
        return max(self.stages.values()) if self.stages else 0


def write_manifest(
    reports: list[ConvertReport],
    manifest_path: Path,
    registry_path: Path,
    project_root: Path,
) -> None:
    manifest: dict[str, Any] = {}
    if manifest_path.is_file():
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))

    for report in reports:
        if report.dry_run or not report.output_files:
            continue
        rel_stages = {
            stage: str(path.relative_to(project_root))
            for stage, path in report.output_files.items()
        }
        manifest[report.dataset] = {
            "stages": rel_stages,
            "samples": report.total_written,
            "role": report.role,
            "skipped": dict(report.skipped),
        }

    registry_lines = [
        "# Auto-generated by tower convert. Copy into NEO neo/data/__init__.py data_dict.",
        "",
        "data_dict = {",
    ]
    for dataset_key in sorted(manifest):
        entry = manifest[dataset_key]
        for stage, rel in sorted(entry.get("stages", {}).items()):
            reg_key = f"{dataset_key}_{stage}"
            abs_path = (project_root / rel).resolve()
            registry_lines.append(f'    "{reg_key}": {{')
            registry_lines.append(f'        "annotation_path": "{abs_path}",')
            registry_lines.append('        "data_path": "",')
            registry_lines.append("    },")
    registry_lines.append("}")

    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    registry_path.write_text("\n".join(registry_lines) + "\n", encoding="utf-8")
