# Auto-generated by tower convert. Copy into NEO neo/data/__init__.py data_dict.

data_dict = {
    "blip3o_long_mt": {
        "annotation_path": "/home/wzk/projects/train_tower/data/processed/mt/blip3o_long.jsonl",
        "data_path": "",
    },
    "blip3o_long_pt": {
        "annotation_path": "/home/wzk/projects/train_tower/data/processed/pt/blip3o_long.jsonl",
        "data_path": "",
    },
    "blip3o_short_mt": {
        "annotation_path": "/home/wzk/projects/train_tower/data/processed/mt/blip3o_short.jsonl",
        "data_path": "",
    },
    "blip3o_short_pt": {
        "annotation_path": "/home/wzk/projects/train_tower/data/processed/pt/blip3o_short.jsonl",
        "data_path": "",
    },
    "chartqa_sft": {
        "annotation_path": "/home/wzk/projects/train_tower/data/processed/sft/chartqa.jsonl",
        "data_path": "",
    },
    "coco2017_mt": {
        "annotation_path": "/home/wzk/projects/train_tower/data/processed/mt/coco2017.jsonl",
        "data_path": "",
    },
    "coco2017_pt": {
        "annotation_path": "/home/wzk/projects/train_tower/data/processed/pt/coco2017.jsonl",
        "data_path": "",
    },
    "coco2017_sft": {
        "annotation_path": "/home/wzk/projects/train_tower/data/processed/sft/coco2017.jsonl",
        "data_path": "",
    },
    "docvqa_sft": {
        "annotation_path": "/home/wzk/projects/train_tower/data/processed/sft/docvqa.jsonl",
        "data_path": "",
    },
    "llava150k_mt": {
        "annotation_path": "/home/wzk/projects/train_tower/data/processed/mt/llava150k.jsonl",
        "data_path": "",
    },
    "llava150k_sft": {
        "annotation_path": "/home/wzk/projects/train_tower/data/processed/sft/llava150k.jsonl",
        "data_path": "",
    },
    "refcoco_mt": {
        "annotation_path": "/home/wzk/projects/train_tower/data/processed/mt/refcoco.jsonl",
        "data_path": "",
    },
    "refcoco_sft": {
        "annotation_path": "/home/wzk/projects/train_tower/data/processed/sft/refcoco.jsonl",
        "data_path": "",
    },
    "sharegpt4v_mt": {
        "annotation_path": "/home/wzk/projects/train_tower/data/processed/mt/sharegpt4v.jsonl",
        "data_path": "",
    },
    "sharegpt4v_sft": {
        "annotation_path": "/home/wzk/projects/train_tower/data/processed/sft/sharegpt4v.jsonl",
        "data_path": "",
    },
    "textcaps_mt": {
        "annotation_path": "/home/wzk/projects/train_tower/data/processed/mt/textcaps.jsonl",
        "data_path": "",
    },
    "textcaps_sft": {
        "annotation_path": "/home/wzk/projects/train_tower/data/processed/sft/textcaps.jsonl",
        "data_path": "",
    },
}
