stage: generation_pt
init_mode: checkpoint
weight_init: random
model_name_or_path: outputs/pretrain/uw_h800
tokenizer_name_or_path: outputs/pretrain/uw_h800
datasets: "blip3o_long_pt,blip3o_short_pt"
loss_weights:
  ce: 0.0
  fm: 1.0
tower_decoder_prob: 0.0
task_override: t2i
tower_self_cond_prob: 0.5
tower_self_cond_cfg_min: 1.0
tower_self_cond_cfg_max: 3.0
cfg_label_drop_prob: 0.15
max_steps: 100000
output_dir: outputs/pretrain/gen_pt_h800
deepspeed: configs/deepspeed/zero2.json
per_device_train_batch_size: 12
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
warmup_steps: 500
max_seq_length: 8192
max_pixels: 8388608
min_pixels: 65536
gradient_checkpointing: false
bf16: true
logging_steps: 10
save_steps: 5000
save_total_limit: 2
dataloader_num_workers: 8
